### ISSUE TITLE
下载的apk 似乎没有反应

### ISSUE THREAD

**Issue by iielse** [nekocode/MusicVisualization#2]

**Comment by Alexander-Huang** [comment]
应该是作者的坑还没有填完😅，现在貌似只做了sa2wave效果，需要给麦克风权限，其他的只有红色背景

**Comment by nekocode** [comment]
需要保证系统音量不为 0 且正在播放音乐

**Comment by Aleksanaa** [comment]
> 需要保证系统音量不为 0 且正在播放音乐

噢，懂了，有时间再试试（话说酷友的github上总能翻腾出一些有意思的小东西<_<）
